package com.pdgc.general.calculation.corporate;

public enum FoxRecordReasonDetail {
	NONE,
	NOT_NEAREST,
	NOT_MAX_CALC_ORDER,
	ORPHAN_RESTRICTION,
	INVALIDATED_BY_OTHER_UNIT_RIGHTS,
	GRANTS_AVAILABILITY,
	PRELIMINARY_DISTRIBUTION,
	RESTRICTS_AVAILABILITY,
	PRIOR_TO_SALES_WINDOW,
	SELECTED_SALES_WINDOW,
	UNSELECTED_SALES_WINDOW,
	EXCEPTION_DEFAULT,
	NO_IMPACT_RESTRICTION,
	UNSELECTED_DRO,
	EXCLUDED_BY_CRITERIA
}
